name: PHPUnit
on: [push, pull_request]
jobs:
    run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [7.2, 7.3, 7.4, 8.0, 8.1]

        name: PHP ${{ matrix.php }}

        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: xdebug
                  extensions: ${{ matrix.extension }}
            - run: composer install --prefer-dist --no-interaction
            - run: vendor/bin/phpunit --coverage-text